package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FocusSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFocusSessionAllPropertiesEquals(FocusSession expected, FocusSession actual) {
        assertFocusSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertFocusSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFocusSessionAllUpdatablePropertiesEquals(FocusSession expected, FocusSession actual) {
        assertFocusSessionUpdatableFieldsEquals(expected, actual);
        assertFocusSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFocusSessionAutoGeneratedPropertiesEquals(FocusSession expected, FocusSession actual) {
        assertThat(actual)
            .as("Verify FocusSession auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFocusSessionUpdatableFieldsEquals(FocusSession expected, FocusSession actual) {
        assertThat(actual)
            .as("Verify FocusSession relevant properties")
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()))
            .satisfies(a -> assertThat(a.getTask()).as("check task").isEqualTo(expected.getTask()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFocusSessionUpdatableRelationshipsEquals(FocusSession expected, FocusSession actual) {
        // empty method
    }
}
