package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReminderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReminderAllPropertiesEquals(Reminder expected, Reminder actual) {
        assertReminderAutoGeneratedPropertiesEquals(expected, actual);
        assertReminderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReminderAllUpdatablePropertiesEquals(Reminder expected, Reminder actual) {
        assertReminderUpdatableFieldsEquals(expected, actual);
        assertReminderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReminderAutoGeneratedPropertiesEquals(Reminder expected, Reminder actual) {
        assertThat(actual)
            .as("Verify Reminder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReminderUpdatableFieldsEquals(Reminder expected, Reminder actual) {
        assertThat(actual)
            .as("Verify Reminder relevant properties")
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getReminderTime()).as("check reminderTime").isEqualTo(expected.getReminderTime()))
            .satisfies(a -> assertThat(a.getRepeatInterval()).as("check repeatInterval").isEqualTo(expected.getRepeatInterval()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReminderUpdatableRelationshipsEquals(Reminder expected, Reminder actual) {
        assertThat(actual)
            .as("Verify Reminder relationships")
            .satisfies(a -> assertThat(a.getTask()).as("check task").isEqualTo(expected.getTask()));
    }
}
